server:
  port: 8080

spring:
  application:
    name: bp20-backend

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB

  main:
    banner-mode: console

logging:
  level:
    root: INFO
    org.springframework.boot: INFO
    org.springframework.web: INFO

ai:
  server-url: http://localhost:8000

llm:
  server-url: http://localhost:8001